name = "news-app"
pages_build_output_dir = ".vercel/output/static"

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
WORDPRESS_HOSTNAME = "https://www.karobarpati.com"
WORDPRESS_URL = "https://www.karobarpati.com"